name: los_espinos_app
description: Los Espinos Glamping - Sistema de Reservas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  cupertino_icons: ^1.0.6
  image: ^4.1.7 
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.7.7
  
  # Google Sign In
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  
  errors:
    invalid_annotation_target: ignore
    todo: ignore
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors: false
    - prefer_const_literals_to_create_immutables: false
    - use_key_in_widget_constructors: false
    - constant_identifier_names: false